#!/bin/sh
#
# _: snake_case filenames
#
# by yury; in the public domain

[ "$1" ] || {
  printf 'usage: %s <files...>\n' "${0##*/}"
  exit 0
}

for file do
  new_file="$(printf '%s' "$file" |
    tr ' ' '_' |
    tr '[:upper:]' '[:lower:]')"
  mv "$file" "$new_file"
  printf '%s → %s\n' "$file" "$new_file"
done
