#!/bin/sh
#
# the [day] today: write a diary
# depends on age(1)
#
# by yury; in the public domain

usage() {
  printf 'usage: %s [yy/mm/dd]\n' "${0##*/}"
  exit 0
}

log() {
  printf '\033[0;3%sm%s\033[0m %s' \
    "${3:-0}" "${2:->}" "$1" >&2
}

die() {
  log "$1" 'ERROR' '1'
  printf '\n'
  exit 1
}

enc() {
  age --encrypt --output "$day" --recipient "$DAY_REC"
}

dec() {
  [ -f "$day" ] ||
    die "${day} is not present."

  # check if clear key exists
  if [ ! -s "${key:=${DAY_KEY%%.age}}" ]; then
    age --decrypt "$DAY_KEY" > "$key" || exit 1

    {
      sleep "${DAY_TIMEOUT:-120}" || kill 0
      rm -f "$key"
    } &
  fi

  age --decrypt --identity "$key" --output - "$day"
}

edit() {
  : "${cleartext:=$(mktemp)}"
  mkdir -p "$yearmonth"
  if [ -f "$day" ]; then
    dec > "$cleartext" ||
      die "unable to decrypt ${day}."
  fi
  "${VISUAL:-$EDITOR}" "$cleartext"
  # shellcheck disable=2002
  cat "$cleartext" | enc
  rm -f "$cleartext"
}

main() {
  mkdir -p "${DAY_DIR:=$HOME/.day}" ||
    die "could not create ${0##*/} directory."

  cd "$DAY_DIR" ||
    die 'could not access directory.'

  [ -f "${DAY_KEY:=$DAY_DIR/.key.age}" ] ||
    age-keygen | age -p > "$DAY_KEY"

  # check if the recipient is set
  [ "$DAY_REC" ] ||
     die 'no recipient is set.'

  # restrict permissions of any new files to only the current user
  umask 077

  # leave terminal usable after exit or Ctrl+C
  [ -t 1 ] &&
    trap 'stty echo icanon' INT EXIT

  if [ "$1" ]; then
    IFS=/
    # shellcheck disable=2086
    set -- $1
  else
    # shellcheck disable=2046
    set -- $(date +'%y %m %d')
  fi

  : "${yearmonth:=${DAY_DIR}/${1}/${2}}"
  : "${day:=${yearmonth}/${3}.age}"

  edit
}

# disable debug mode to prevent leakage
set +x

# disable globbing to avoid word-splitting
set -f

main "$@"
