#!/bin/sh
#
# mkclip: make a clip
# depends on ffmpeg(1)
#
# t.me/digitalarcheology/694; in the public domain

[ "$1" ] || {
  printf 'usage: %s <image> <audio> [output]\n' "${0##*/}"
  exit 0
}

ffmpeg             \
  -i "$1"          \
  -f image2        \
  -loop 1          \
  -r 25            \
  -i "$2"          \
  -vf scale=512:-1 \
  -shortest        \
  -vcodec libx264  \
  -pix_fmt yuv420p \
  -acodec aac      \
  -y               \
  -profile:v baseline "${3:-output.mp4}"
