#!/bin/sh
#
# mp3: download an mp3
# depends on youtube-dl(1)
#
# by yury; in the public domain

${YOUTUBE_DL:-yt-dlp} \
  --extract-audio     \
  --embed-thumbnail   \
  --audio-format mp3  \
  "$@"
