#!/bin/sh
#
# ram[en]: memory usage
#
# by yury; in the public domain

mem_full=$(($(sysctl -n hw.memsize) / 1024 / 1024))

while IFS=:. read -r key val; do
  case $key in
  *' wired'* | *' active'* | *' occupied'*)
    mem_used=$((mem_used + ${val:-0})) ;;
  esac
done <<-EOF
  $(vm_stat)
EOF

mem_used=$((mem_used * 4 / 1024))

printf '%sM / %sM\n' "${mem_used:-?}" "${mem_full:-?}"
