#!/bin/sh
#
# batd: low battery level alert
# depends on xbacklight(1)
#
# by yury; in the public domain

read -r bat_lvl </sys/class/power_supply/BAT1

[ "$bat_lvl" = 'unknown' ] || [ "$bat_lvl" -gt 20 ] && exit 0

export DISPLAY=:0

for bri in 0 50 0 50; do
  xbacklight -set "$bri"
done

exit 1
